import pandas as pd

from GenAI.llm import client
from GenAI.prompt import SYSTEM_PROMPT

# Load dataset only once
df = pd.read_csv("cleaned_crime_dataset.csv")

# Keywords related to the dataset
DATASET_KEYWORDS = [
    "crime",
    "crimes",
    "city",
    "cities",
    "victim",
    "victims",
    "weapon",
    "gender",
    "age",
    "age group",
    "police",
    "case",
    "cases",
    "closed",
    "closure",
    "crime domain",
    "crime description",
    "crime code",
    "report",
    "occurrence",
    "occurred",
    "murder",
    "theft",
    "robbery",
    "fraud",
    "kidnapping",
    "assault",
    "cyber",
    "domestic",
    "violence"
]


def ask_ai(question):
    """
    Ask questions only about the uploaded crime dataset.
    """

    question_lower = question.lower().strip()

    # Reject unrelated questions before calling the LLM
    if not any(keyword in question_lower for keyword in DATASET_KEYWORDS):
        return (
            "❌ This question cannot be answered from the uploaded crime dataset.",
            "Please ask a question related to the uploaded crime dataset."
        )

    # Ask Groq to generate Pandas code
    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {
                    "role": "system",
                    "content": SYSTEM_PROMPT
                },
                {
                    "role": "user",
                    "content": question
                }
            ],
            temperature=0
        )

    except Exception as e:
        raise RuntimeError(f"Groq Error:\n{e}")

    code = response.choices[0].message.content.strip()

    # Remove markdown if present
    code = code.replace("```python", "")
    code = code.replace("```", "")
    code = code.strip()

    # Security checks
    blocked_words = [
        "import",
        "open(",
        "exec(",
        "eval(",
        "__",
        "os.",
        "sys.",
        "subprocess",
        "shutil",
        "pickle"
    ]

    for word in blocked_words:
        if word in code.lower():
            raise RuntimeError("Unsafe code generated by the AI.")

    local_scope = {"df": df.copy()}

    # Execute generated Pandas code
    try:
        exec(code, {}, local_scope)

        if "result" not in local_scope:
            raise RuntimeError("AI did not return a variable named 'result'.")

        result = local_scope["result"]

    except Exception as e:
        raise RuntimeError(
            f"""
Generated Code:

{code}

Execution Error:

{e}
"""
        )

    # Ask Groq to explain the result
    try:
        explanation = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {
                    "role": "system",
                    "content": """
Explain the result ONLY using the provided output.

Do not add extra facts.

Do not use outside knowledge.

Keep the explanation under 100 words.
"""
                },
                {
                    "role": "user",
                    "content": f"""
Question:
{question}

Result:
{result}
"""
                }
            ],
            temperature=0
        )

        explanation_text = explanation.choices[0].message.content

    except Exception:
        explanation_text = "Explanation could not be generated."

    return result, explanation_text